apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.48.0
    chart: grafana
    helm:
      values: |
        ingress:
          enabled: false
        serviceMonitor:
          enabled: true
        grafana.ini:
          server:
            domain: grafana.local
            root_url: "%(protocol)s://%(domain)/"
            auth.ldap:
              enabled: true
              allow_sign_up: true            
        ldap:
          enabled: true
          config: |-
            [[servers]]
            host = "192.168.57.10"
            port = 389
            use_ssl = false
            search_filter = "(uid=%s)"
            search_base_dns = ["dc=nixos,dc=org"]
            group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
            group_search_filter_user_attribute = "uid"
            group_search_base_dns = ["dc=nixos,dc=org"]
            [servers.attributes]
            email =  "email"
            [[servers.group_mappings]]
            group_dn = "cn=admins,ou=Roles,dc=nixos,dc=org"
            org_role = "Admin"
            grafana_admin = true            
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: "http://prometheus-operated:9090"
              isDefault: true
            - name: Loki
              type: loki
              url: "http://loki:3100/"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true