apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus-operator.yaml
- prometheus-cluster.yaml
- loki.yaml
- promtail.yaml
- grafana.yaml
- rabbitmq-cluster-app.yaml
- rabbitmq-operator-app.yaml
- redis-app.yaml