apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 3.6.1
    chart: loki
    helm:
      values: |
        monitor:
          serviceMonitor:
            enabled: true
        write:
          replicas: 1
        read:
          replicas: 1
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem

          schemaConfig:
            configs:
              - from: "2022-12-01"
                store: boltdb-shipper
                object_store: filesystem
                schema: v11
                index:
                  period: 24h
                  prefix: loki_index_            
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true