apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/necrophcodr/k3d-demo-repo'
    path: deployments/demo/redis
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
